declare module 'lucide-react' {
  import type * as React from 'react'

  export type LucideIcon = React.ComponentType<React.SVGProps<SVGSVGElement>>

  export const ArrowDown: LucideIcon
  export const ArrowUpRight: LucideIcon
  export const ArrowRight: LucideIcon
  export const ArrowLeft: LucideIcon
  export const CheckCircle: LucideIcon
  export const Calendar: LucideIcon
  export const Clock: LucideIcon
  export const Sparkles: LucideIcon
  export const User: LucideIcon
  export const Share: LucideIcon
  export const ExternalLink: LucideIcon
  export const Github: LucideIcon
  export const BookOpen: LucideIcon
  export const Terminal: LucideIcon
  export const HelpCircle: LucideIcon
  export const Settings: LucideIcon
  export const Package: LucideIcon
  export const Truck: LucideIcon
  export const Monitor: LucideIcon
  export const PackageIcon: LucideIcon
  export const Blocks: LucideIcon
  export const AlertTriangle: LucideIcon
  export const CalendarDays: LucideIcon
  export const ClipboardList: LucideIcon
  export const CreditCard: LucideIcon
  export const Zap: LucideIcon
  export const Plane: LucideIcon
  export const DollarSign: LucideIcon
  export const Download: LucideIcon
  export const FileText: LucideIcon
  export const Power: LucideIcon
  export const Lightbulb: LucideIcon
  export const Radar: LucideIcon
  export const Database: LucideIcon
  export const Beaker: LucideIcon
  export const Wrench: LucideIcon
  export const Play: LucideIcon
  export const Eye: LucideIcon
  export const Wind: LucideIcon
  export const Shield: LucideIcon
  export const Cable: LucideIcon
  export const ChevronDownIcon: LucideIcon
  export const ChevronLeftIcon: LucideIcon
  export const ChevronRightIcon: LucideIcon
  export const MoreHorizontalIcon: LucideIcon
  export const ListChecks: LucideIcon
  export const MessageSquare: LucideIcon
  export const ZapOff: LucideIcon
  export const Mail: LucideIcon
  export const ShoppingCart: LucideIcon
  export const DownloadIcon: LucideIcon
  export const MessageCircle: LucideIcon
  export const AlertCircle: LucideIcon
  export const PlayIcon: LucideIcon
  export const X: LucideIcon
  export const Search: LucideIcon
  export const Twitter: LucideIcon
  export const Linkedin: LucideIcon
  export const ComputerIcon: LucideIcon
  export const Move3DIcon: LucideIcon
  export const VideotapeIcon: LucideIcon
  export const Code2: LucideIcon
  export const CircuitBoard: LucideIcon
  export const Menu: LucideIcon
  export const ChevronRight: LucideIcon
  export const TrendingDownIcon: LucideIcon
  export const TrendingUpIcon: LucideIcon
  export const Users: LucideIcon
  export const Code: LucideIcon
  export const Building2: LucideIcon
  export const MapPin: LucideIcon
  export const Info: LucideIcon
}
