export const team = [
	{
		name: "Elliott Rouse, PhD",
		role: "Principal Investigator",
		title: "Associate Professor",
		imageUrl: "/people/elliott.webp",
		profileUrl: "https://www.linkedin.com/in/elliott-rouse-6933757/",
		affliation: "U-M Robotics",
	},
	{
		name: "Senthur Ayyappan",
		role: "Project Lead & Maintainer",
		title: "Research Engineer",
		imageUrl: "/people/senthur.webp",
		profileUrl: "https://www.linkedin.com/in/imsenthur/",
		affliation: "U-M Robotics",
	},
	{
		name: "Itzel Fer, MD",
		role: "Clinical Lead",
		title: "",
		imageUrl: "/people/Itzel.jpeg",
		profileUrl: "",
		affliation: "U-M Robotics",
	},
	{
		name: "Kiara Vasquez",
		role: "Marketing & Community Coordinator",
		title: "",
		imageUrl: "/people/kiara.webp",
		profileUrl: "https://www.linkedin.com/in/k1aara/",
		affliation: "U-M Robotics",
	},
	{
		name: "Alejandro F. Azocar, PhD",
		role: "",
		title: "Biomechatronics Engineer",
		imageUrl: "/people/alejandro.webp",
		profileUrl: "",
		affliation: "Apple",
	},
	{
		name: "Ung Hee Lee, PhD",
		role: "",
		title: "Software Engineer",
		imageUrl: "/people/unghee.webp",
		profileUrl: "",
		affliation: "Nuro",
	},
	{
		name: "Mo Miro",
		role: "",
		title: "Simulation Engineer",
		imageUrl: "/people/mo.webp",
		profileUrl: "",
		affliation: "Stellantis",
	},
	{
		name: "Enis Habib",
		role: "",
		title: "Business Engineer",
		imageUrl: "/people/enis-habib.webp",
		profileUrl: "",
		affliation: "Habib Makina",
	},	
	{
		name: "Kevin Best, PhD",
		role: "Researcher",
		title: "Researcher",
		imageUrl: "/people/kevin.webp",
		profileUrl: "",
		affliation: "U-M Robotics",
	},
	{
		name: "Japmanjeet Singh Gill",
		role: "Researcher",
		title: "PhD Candidate",
		imageUrl: "/people/japmanjeet.webp",
		profileUrl: "",
		affliation: "U-M Robotics",
	},
	{
		name: "Zach Bons",
		role: "Researcher",
		title: "PhD Candidate",
		imageUrl: "/people/zach.webp",
		profileUrl: "",
		affliation: "U-M Robotics",
	},	
	{
		name: "Varun Satyadev Shetty",
		role: "Researcher",
		title: "PhD Candidate",
		imageUrl: "/people/varun.jpg",
		profileUrl: "",
		affliation: "U-M Robotics",
	},	
	{
		name: "Ellie Wilson",
		role: "Researcher",
		title: "PhD Candidate",
		imageUrl: "/people/ellie.jpg",
		profileUrl: "",
		affliation: "U-M Robotics",
	},		
	{
		name: "Ryan Posh, PhD",
		role: "Researcher",
		title: "Post Doc",
		imageUrl: "/people/ryan.jpg",
		profileUrl: "",
		affliation: "U-M Robotics",
	},	
	{
		name: "Jace Derosia",
		role: "Research Intern",
		title: "Undergraduate Student",
		imageUrl: "/people/jace.webp",
		profileUrl: "",
		affliation: "U-M Robotics",
	},
	{
		name: "Elissa Cimino",
		role: "Research Intern",
		title: "Undergraduate Student",
		imageUrl: "/people/elissa.webp",
		profileUrl: "",
		affliation: "Univ. of Miami BME",
	},
	{
		name: "Yuanshao Yang",
		role: "Research Intern",
		title: "Undergraduate Student",
		imageUrl: "/people/yuanshao.webp",
		profileUrl: "",
		affliation: "U-M ME",
	},
	{
		name: "Anuhea Tao",
		role: "Research Intern",
		title: "Undergraduate Student",
		imageUrl: "/people/anuhea.webp",
		profileUrl: "",
		affliation: "U-M Robotics",
	},
	{
		name: "Jiarui Gu",
		role: "Research Intern",
		title: "Undergraduate Student",
		imageUrl: "/people/jiarui.webp",
		profileUrl: "",
		affliation: "U-M ME",
	},
	{
		name: "Unsh Rawal",
		role: "Research Intern",
		title: "Undergraduate Student",
		imageUrl: "/people/unsh.webp",
		profileUrl: "",
		affliation: "UT Austin",
	},	
	{
		name: "Raphael Allusson",
		role: "Research Intern",
		title: "Undergraduate Student",
		imageUrl: "/people/raphael.webp",
		profileUrl: "",
		affliation: "U-M Robotics",
	},
	{
		name: "Pranav Ganesh Ram",
		role: "Research Intern",
		title: "Undergraduate Student",
		imageUrl: "/people/pranav.webp",
		profileUrl: "",
		affliation: "NIT Trichy",
	},		
	{
		name: "John Kotarski",
		role: "Research Intern",
		title: "Undergraduate Student",
		imageUrl: "/people/john.webp",
		profileUrl: "",
		affliation: "U-M ECE",
	},
	{
		name: "Elena Sharnowski",
		role: "Research Intern",
		title: "Undergraduate Student",
		imageUrl: "/people/elena.webp",
		profileUrl: "",
		affliation: "U-M ECE",
	},	
	{
		name: "Alan Tondryk",
		role: "Research Intern",
		title: "Graduate Student",
		imageUrl: "/people/alan.webp",
		profileUrl: "",
		affliation: "U-M Robotics",
	},
	{
		name: "Kefan Zheng",
		role: "Research Intern",
		title: "Graduate Student",
		imageUrl: "/people/kefan.webp",
		profileUrl: "",
		affliation: "U-M Robotics",
	},

	{
		name: "Ariela Warticovschi",
		role: "Research Intern",
		title: "Undergraduate Student",
		imageUrl: "/people/ariela.webp",
		profileUrl: "",
		affliation: "U-M Robotics",
	},
	{
		name: "Brenda Ahearn",
		role: "Media",
		title: "Photographer",
		imageUrl: "/people/brenda.webp",
		profileUrl: "",
		affliation: "U-M COE",
	},	
];

export const alumni = [
	{
		name: "Levi Hargrove, PhD",
		role: "",
		title: "Associate Professor",
		imageUrl: "/people/levi.jpeg",
		profileUrl: "",
		affliation: "Northwestern University",
	},
	{
		name: "Robert Gregg, PhD",
		role: "",
		title: "Associate Professor",
		imageUrl: "/people/bobby.jpg",
		profileUrl: "",
		affliation: "U-M Robotics",
	},
	{
		name: "Luke Mooney, PhD",
		role: "",
		title: "CEO",
		imageUrl: "/people/luke.jpeg",
		profileUrl: "",
		affliation: "Dephy, Inc.",
	},
	
];

export interface TeamMember {
	name: string;
	role: string;
	title: string;
	imageUrl: string;
	profileUrl: string;
	affliation: string;
} 